---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(RANN)
library(leaflet)
library(sp)
```

           

```{r}
All_Mosquito<- read.csv("~/Dropbox/SLE/All_mosquito_complete.csv",header = TRUE)
View(mosquito_data)

stan_data<-read.csv("~/Dropbox/Bayes/Model/stan_data.csv")

Trap_ID <- All_Mosquito$Trap.ID[!duplicated(All_Mosquito$Trap.ID)]
Trap_lat <- All_Mosquito$Latitude[!duplicated(All_Mosquito$Trap.ID)]
Trap_long <- All_Mosquito$Longitude[!duplicated(All_Mosquito$Trap.ID)]
Trap_ID_RT <- Trap_ID[grep(pattern = "RT.*",x = Trap_ID)]
Trap_lat_RT <- Trap_lat[grep(pattern = "RT.*",x = Trap_ID)]
Trap_long_RT <- Trap_long[grep(pattern = "RT.*",x = Trap_ID)]

trap_db <- data.frame(Trap_ID = Trap_ID_RT, Latitude = Trap_lat_RT, Longitude = Trap_long_RT)

head (trap_db)


Lat_long_weather_stations <- read.csv("~/Dropbox/SLE/Maricopa_WeatherStations/Precip_and_other_table.csv", header = TRUE)

  distances <- nn2(data =Lat_long_weather_stations[,c("Latitude", "Longitude")] , query = trap_db[,2:3],k = 2  )

  
  weath_names_trap <- c()
  longitude_weath <- c()
  latitude_weath <- c()
  count = 1
for( i in distances$nn.idx[,1]){
  weath_names_trap[count] <- as.character(Lat_long_weather_stations$Station_ID[i])
  longitude_weath[count] <- Lat_long_weather_stations$Longitude[i]
  latitude_weath[count] <- Lat_long_weather_stations$Latitude[i]
  count = count + 1
}  

  
trap_db <- cbind(trap_db,weath_names_trap,index = distances$nn.idx[,1],longitude_weath,latitude_weath)

write.csv(trap_db, "~/Dropbox/SLE/Maricopa_WeatherStations/Trap_Weather_Station_paired.csv",row.names = FALSE)

  
      
View(trap_db  )
```



```{r}




cool <- apply(Lat_long_weather_stations[,c("Longitude","Latitude")],2,as.numeric)
#cool <- cool[1:5,]
cool <- SpatialPoints(cool)


#coordinates(cool) <- ~x+y

traps2<-read.csv("~/Dropbox/Bayes/Model/lat_long_traps.csv", header = TRUE)

typeof(cool)
#traps<-read.csv("~/Dropbox/Bayes/Model/lat_long_traps.csv", header = TRUE)
traps <- trap_db[,2:3]
traps <- traps[,c(2,1)]
head(traps)

traps <- SpatialPoints(traps)



leaflet() %>% addProviderTiles("OpenStreetMap") %>% addMarkers(lng = traps@coords[,1], lat = traps@coords[,2],
             label = trap_db$Trap_ID) %>% addCircleMarkers(lng = Lat_long_weather_stations$Longitude, lat = Lat_long_weather_stations$Latitude,
             label = Lat_long_weather_stations$Station_ID)

mapview(cool)

```



```{r}
paired_weath_trap<- read.csv("~/Dropbox/SLE/Maricopa_WeatherStations/Trap_Weather_Station_paired.csv", header = TRUE, stringsAsFactors = FALSE)

data_input<-read.csv("~/Dropbox/Bayes/Model/stan_data.csv")


stan_lat <- paired_weath_trap[,2][paired_weath_trap[,1] %in%  names(data_input)[6:18]]
stan_long <- paired_weath_trap[,3][paired_weath_trap[,1] %in%  names(data_input)[6:18]]


stan_sp <- cbind(stan_long,stan_lat)
colnames(stan_sp) <- c("Longitude","Latitude")
stan_sp <- SpatialPoints(stan_sp)


leaflet() %>% addProviderTiles("OpenStreetMap") %>% addCircleMarkers(lng = stan_sp@coords[,1], lat = stan_sp@coords[,2],color = "black",weight = 1,opacity = 1,
             label = trap_db$Trap_ID,fillColor = "black",radius = 5) %>% addCircleMarkers(lng = Lat_long_weather_stations$Longitude, lat = Lat_long_weather_stations$Latitude,label = Lat_long_weather_stations$Station_ID,color = "black",weight = 1,opacity = 1,fillColor = "Orange",fillOpacity = 0.8,stroke = TRUE,radius = 5)%>% addLegend(position = "bottomright",colors = c("black","Orange"), labels = c("Mosquito Trap","Weather Station"), opacity = 1)


leaflet() %>% addProviderTiles("OpenStreetMap") %>% addCircleMarkers(lng = traps@coords[,1], lat = traps@coords[,2],color = "black",weight = 1,opacity = 1,
             label = trap_db$Trap_ID,fillColor = "black",radius = 2,fillOpacity = 1)%>% addLegend(position = "bottomright",colors = "black", labels = c("Mosquito Trap"), opacity = 1)
```

