---
title: "SLE_Tree"
output: html_document
---

```{r}
library(ggplot2)
library(ggtree)

library(tidytree)
library(ape)

Primer_Scheme_Ends<-function(primer_file){

  primer_range_begin <- primer_file$End[grepl(".*LEFT",primer_file$Primer.Name,perl=TRUE)]
  primer_range_end <- primer_file$End[grepl(".*RIGHT",primer_file$Primer.Name,perl=TRUE)]
  
  return(cbind(primer_range_begin,primer_range_end))
}

primer_scheme_Names<-function(primer_file){

full_names <- primer_file$Primer.Name[grepl(".*RIGHT",primer_file$Primer.Name,perl=TRUE)]
split_primer_names <- as.vector(strsplit(x = as.character(full_names), split = "\\_R",perl = TRUE))
primer_names <- apply(as.array(split_primer_names),1,function(x) x[[1]][1])

return(primer_names)
}

primer_database <- function(primer_file,colors=c("purple","orange")){
  primers<-read.csv(primer_file,header = TRUE, na.strings = c("","NA"),stringsAsFactors = FALSE)

  primer_done<-Primer_Scheme_Ends(primers)
  primer_names<-primer_scheme_Names(primers)
  
  rownames(primer_done)<- primer_names
  
  pools <- c()
  primer_color <- c()
  height <- c(200,1000)
  y_height<-c()
  count = 1
  index = 1
  for (i in 1:nrow(primer_done)){
    if (primers[count, "Pool"] == 1){
      pools[index] = "Pool1"
      primer_color[index] <- colors[1]
      y_height[index] <- height[1]
    }else{
      pools[index] = "Pool2"
      primer_color[index] <- colors[2]
       y_height[index] <- height[2]
    }
    count = count + 2
    index = index + 1
    
  }
  
  primer_done <- cbind(primer_done, pools,primer_color)
  
  
  return(primer_done)
  
  }

save.image(file = "primer_function.RData")


test<-primer_database("~/Dropbox/SLE/Primers/SLEV_Primal_Scheme_051518.csv",c("red","green"))
test

(test_plot<-ggplot()+
  
geom_segment(data = as.data.frame(test),aes(x=as.numeric(test[,1]),y=head(rep(c(200,1000), nrow(test))/2,-1),xend = as.numeric(test[,2]), yend = head(rep(c(200,1000)), nrow(test)/2,-1),color = test[,4]),size = 3)+
scale_color_manual(values=c("blue", "green"))+
ylim(0,2000)+
  geom_segment(aes(x=0,y=0,xend = 10936, yend = 0),size = 2,color = "Purple"))
  

  
  geom_text(aes(x=(as.numeric(test[,1])+as.numeric(test[,2]))/2, y = k+110, label = rownames(test)),size =4,nudge_y = 5, fontface = "bold")+
  
  coord_fixed()+
  theme_classic()+
   labs(title = "",color = "Primer Pools")+
  xlab("Genome Location")+
  ylab("")+
  theme(plot.title = element_text(hjust = 0.5),axis.text.y = element_text(color = "white"),axis.line.y = element_line(color = "white"), axis.ticks.y = element_line(color = "white") ))





rownames(primer_done) <- primer_names
pools12<-head(rep(c("pool1","pool2"), 21),-1)
pools123<-head(rep(c("pool1","pool2"), 21),-1)
pool3 <- c(4,7,10,12,17,19,23,25,26,31,41)
pools123[pool3] = "pool3"


primer_done = primer_done[,1:2]
primer_done12= primer_done[,1:2]
primer_done <- cbind(primer_done,pools123)
primer_done12<-cbind(primer_done12,pools12)
```

```{r}

j <- seq(1,nrow(primer_done),1)
j<-runif(nrow(primer_done),0, 1)
j<- head(rep(c(200,1000), 21),-1)


k <- seq(1,41,1)
k<-runif(41,0, 1)
k<- head(rep(c(200,1000), 21),-1)

color_primer <- primer_done[,3]
color_primer[color_primer == "pool1"] <- "blue"
color_primer[color_primer == "pool2"] <- "green"
color_primer[color_primer == "pool3"] <- "red"
#################################################################################
##                      Plots The Primers
###############################################################################
Pool12_tiled<-ggplot()+
  
geom_segment(aes(x=as.numeric(primer_done12[,1]),y=k,xend = as.numeric(primer_done12[,2]), yend = k,color = primer_done12[,3]),size = 3)+
scale_color_manual(values=c("blue", "green"))+
ylim(0,2000)+

  geom_segment(aes(x=0,y=0,xend = 10936, yend = 0),size = 2,color = "Purple")+
  
  geom_text(aes(x=(as.numeric(primer_done12[,1])+as.numeric(primer_done12[,2]))/2, y = k+110, label = rownames(primer_done12)),size =4,nudge_y = 5, fontface = "bold")+
  
  coord_fixed()+
  theme_classic()+
   labs(title = "",color = "Primer Pools")+
  xlab("Genome Location")+
  ylab("")+
  theme(plot.title = element_text(hjust = 0.5),axis.text.y = element_text(color = "white"),axis.line.y = element_line(color = "white"), axis.ticks.y = element_line(color = "white") )

ggsave(file="~/Dropbox/SLE/Committee_Meeting/Pool12.png", plot= Pool12_tiled, device = "png", width = 20, height = 12, units = "in",limitsize = F)

####Plots Pool3 and circles
(Pool3_tiled<- ggplot()+
  
geom_segment(aes(x=as.numeric(primer_done[,1]),y=j,xend = as.numeric(primer_done[,2]), yend = j,color = primer_done[,3],size = 3))+
scale_color_manual(breaks = c("pool1","pool2","pool3"),values=c("blue", "green", "red"))+
ylim(0,2000)+

  geom_segment(aes(x=0,y=0,xend = 10936, yend = 0),size = 2,color = "Purple")+
  
  geom_text(aes(x=(as.numeric(primer_done[,1])+as.numeric(primer_done[,2]))/2, y = j+110, label = rownames(primer_done)),size = 4,nudge_y = 20,fontface = "bold")+
  coord_fixed()+
  #geom_point(mapping = aes(x = (as.numeric(primer_done[primer_done[,3]=="pool3",1])+as.numeric(primer_done[primer_done[,3]=="pool3",2]))/2, y = j[primer_done[,3]=="pool3"]),size = 15,shape = 1,color = "red")+
  theme_classic()+
   labs(title = "",color ="Primer Pools")+
  xlab("Genome Location")+
  ylab("")+
  theme(plot.title = element_text(hjust = 0.5),axis.text.y = element_text(color = "white"),axis.line.y = element_line(color = "white"), axis.ticks.y = element_line(color = "white") ))
  
ggsave(file="~/Dropbox/SLE/Committee_Meeting/Pool3.png", plot= Pool3_tiled, device = "png", width = 20, height = 12, units = "in")
  

```



